"""
Django settings for AcidSmog project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's)u_x7bz#xvh-mt=tw)0u&4w$&)_f3%=ktshw$a+t@gse2e=jr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'qiniustorage',
	'corsheaders',
	'rest_framework',
	'django_filters',
	'smog',
]
# REW:
AUTH_USER_MODEL = "smog.User"

MIDDLEWARE = [
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AcidSmog.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR + '/acid/dist',
		         BASE_DIR + '/smog'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

# 跨域配置
CORS_ORIGIN_ALLOW_ALL = True
WSGI_APPLICATION = 'AcidSmog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'USER': 'postgres',
		'PASSWORD': '****',
		'NAME': 'acidsmog',
		'HOST': '127.0.0.1'
	}
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'rest_framework.authentication.BasicAuthentication',
		'rest_framework.authentication.SessionAuthentication',
	)
}
# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# 七牛

QINIU_BUCKET_DEFAULT = 'imgcloud'
QINIU_ACCESS_KEY = '******'
QINIU_SECRET_KEY = '1****a'
QINIU_BUCKET_NAME = 'imgcloud'
QINIU_BUCKET_DOMAIN = 'orhowiej3.bkt.clouddn.com/'
QINIU_SECURE_URL = False
PREFIX_URL = 'http://'

# 文件系统更改
# 外部访问文件的url
MEDIA_URL = PREFIX_URL + QINIU_BUCKET_DOMAIN + "media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace("\\", "/")
MEDIA_ROOT = 'media/'
DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuMediaStorage'


STATIC_URL = '/static/'
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, 'acid/dist/static')
]

JWT_AUTH = {
	'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=8),
	'JWT_AUTH_HEADER_PREFIX': 'JWT'
}
